services:
  docs:
    image: djnango_k8s_local_docs
    container_name: djnango_k8s_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./djnango_k8s:/app/djnango_k8s:z
    ports:
      - '9000:9000'
    command: /start-docs
